export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"



export const REGISTER_REQUEST="REGISTER_REQUEST"
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAIL="REGISTER_FAIL"


export const LOAD_REQUEST="LOAD_REQUEST"
export const LOAD_SUCCESS="LOAD_SUCCESS"
export const LOAD_FAIL="LOAD_FAIL"

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"


export const VIDEO_REQUEST="VIDEO_REQUEST"
export const VIDEO_SUCCESS="VIDEO_SUCCESS"
export const VIDEO_FAIL="VIDEO_FAIL"
export const VIDEO_CLEAR="VIDEO_CLEAR"


export const SINGLE_VIDEO_REQUEST="SINGLE_VIDEO_REQUEST"
export const SINGLE_VIDEO_SUCCESS="SINGLE_VIDEO_SUCCESS"
export const SINGLE_VIDEO_FAIL="SINGLE_VIDEO_FAIL"
export const CLEAR_SINGLE_VIDEO="CLEAR_SINGLE_VIDEO"



export const CLEAR_ERROR="CLEAR_ERROR"




